### ISSUE TITLE
Getting errors on SkinLesion dataset

### ISSUE THREAD

**Issue by SahadevPoudel** [xmengli999/TCSM#1]
Hi, I run this code with default settings i.e. Pytorch 1.1 and cuda 9.0.  I have installed cuda 9.0 and Cudnn version 7.6.5. However, i am getting this error.

   RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
Especially, it is marking loss.backward()

Could you help me?

**Comment by urkax** [comment]
@SahadevPoudel Hi~ I solved the problem. This error occurs because the value of targets (0 or 255) is bigger than class (2). So you should add a line in __getitem__ of class skinlesion_labeled in skinlesion.py before return:
`target = (target > 0).type(torch.int)`

**Comment by SahadevPoudel** [comment]
> @SahadevPoudel Hi~ I solved the problem. This error occurs because the value of targets (0 or 255) is bigger than class (2). So you should add a line in __getitem__ of class skinlesion_labeled in skinlesion.py before return:
> `target = (target > 0).type(torch.int)`
It works. Thank you a lot.
